name: the_eye
description: "The Eye is a parental controlled video player for kids.
It allows parents to control the videos their kids watch."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pod_player: ^0.2.1
  cloud_firestore: ^4.15.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  google_sign_in: ^6.0.2
  firebase_storage: ^11.5.6
  flutter_screenutil: ^5.9.0
  flutter_credit_card: ^4.0.1
  credit_card_scanner: ^1.0.5
  multi_value_listenable_builder: ^0.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.10
  fl_chart: ^0.66.2
  file_picker: ^8.0.0+1
  amplify_flutter: ^1.7.0
  amplify_auth_cognito: ^1.7.2
  amplify_storage_s3: ^1.7.0
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/jua/Jua-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
